#!/usr/bin/python3

# This python script reads in a parameters.yaml file as generated by
# AxiSEM3D that contains information about all possible parameters and
# converts them to Markdown files which are used to generate AxiSEM3D's 
# online parameter documentation.
import yaml

# A recursive function to convert the python object into markdown
def yamlToMarkdown(object):
    if type(object) is dict:
        for key, value in object.items():
            print(key)

            if (type(value) is dict):
                yamlToMarkdown(value)
            elif (type(value) is list):
                for item in value:
                    if (type(item) is dict):
                        yamlToMarkdown(item)
                    else:
                        print(item)
            else:
                print(value)

with open("parameters.yaml", "r") as f:
    data = yaml.safe_load(f)

yamlToMarkdown(data)


